### ISSUE TITLE
Question about cable and how to config wave share

### ISSUE THREAD

**Issue by mworion** [Privatecoder/seplos-mqtt-remote-rs485#1]
Privatecoder,

First, congrats to this excellent solution. Still I'm struggling with it as I need to config the waveshare device and need to do the wires. Could you give some help ? I really appreciate your work !

Michel

**Comment by Privatecoder** [comment]
Hi Michel,

I suggest you take a regular patch-cable and cut one of the connectors. Then you take the `orange`, `orange-white` and `green-white` wires, crimp a terminal onto them and connect them to the waveshare device like this:

- `orange` => `RS485-A`
- `orange-white` => `RS485-B`
- `green-white` => `PE`

This works for both, Masters via the splitter (Baud 9600) and Slaves to an empty RS485 port of the BMS (Baud 19200).

![waveshare-pins](https://github.com/Privatecoder/seplos-mqtt-remote-rs485/assets/45964815/34d5e8f3-43dd-46a6-8baf-5d9af662837d)

**Comment by mworion** [comment]
Hi Privatecoder,
many thanks, did so, should work. Any ideas how to check if the waveshare receives the data ? I currently do not see the remote serial links in your source. You talk about a docker image. Is there any dependency about this ? And if, which one to use to use the remote RS-485 right.
Michel

**Comment by Privatecoder** [comment]
When using VirCom in Windows, how do your settings look like? Can you provide a screenshot?

As for the remote serial-link question: The Docker image uses socat which is able to create a remote-tcp-serial to local virtual-com-port _bridge_, which is then used by the script. No other components are required in this case.

**Comment by Privatecoder** [comment]
..also waveshare provides a tool called `sscom`. If you open that and connect to your waveshare device via the `TCPClient` option you will see intra-pack-communication when running multiple packs in parallel (in my case, the waveshare device connected to the slaves in this example has IP 192.168.100.59).

<img width="226" alt="image" src="https://github.com/Privatecoder/seplos-mqtt-remote-rs485/assets/45964815/1b072ee2-b29a-418f-a0bd-966907588ae6">

**Comment by mworion** [comment]
As I'm on a Mac, Windows solutions do normally not match. I integrated this now in w windows machine:
![Bildschirmfoto 2024-01-28 um 14 34 29](https://github.com/Privatecoder/seplos-mqtt-remote-rs485/assets/6632980/cde641b1-42a7-4533-8904-98ddf5dbccf4)
Is it possible to rund it without a docker (as you are using the docker mainly for running socat to get the remote RS-485 ?

**Comment by Privatecoder** [comment]
I am also on a Mac using Windows in a vm. Click on "Device" and then of the two devices with their configs and post them.

**Comment by mworion** [comment]
![Bildschirmfoto 2024-01-28 um 15 23 48](https://github.com/Privatecoder/seplos-mqtt-remote-rs485/assets/6632980/5fb35055-db09-4fb3-baf6-72ee5c73f992)
![Bildschirmfoto 2024-01-28 um 15 24 11](https://github.com/Privatecoder/seplos-mqtt-remote-rs485/assets/6632980/d699e972-5e85-4822-b387-be9f3c7d911d)

**Comment by Privatecoder** [comment]
When connecting to a master via a splitter, set baud-rate in the waveshare-settings to 9600, if you are connecting to a slave, set it to 19200. Right now your baud-rate is set to 115200 from what I can see in the screenshot above.

**Comment by mworion** [comment]
Ok, trying. Many thanks so far. I need some more time to check and test. I'll come back.
Michel

**Comment by Privatecoder** [comment]
Just to be sure – these are my settings for the waveshare device, wehere `Seplos#1` is for the connection to the Master (`pack-0`) and `Seplos#2` for the Slaves (`pack-1`-`n`):
<img width="848" alt="SCR-20240128-plhw" src="https://github.com/Privatecoder/seplos-mqtt-remote-rs485/assets/45964815/5311d248-b35f-40d4-afb5-114096772679">
<img width="851" alt="SCR-20240128-plmc" src="https://github.com/Privatecoder/seplos-mqtt-remote-rs485/assets/45964815/c7b48108-e991-4c4f-b778-6b574b8df8c2">

**Comment by Privatecoder** [comment]
also I see your device's firmware is old. consider checking [this thread](https://github.com/alienatedsec/solis-ha-modbus-cloud/discussions/17) to update it.

**Comment by mworion** [comment]
OK, got it. There is one topic I do not understand: I use the same waveshare with two ports, but only get one device -> this might be the problem.
Michel

**Comment by mworion** [comment]
Sorry missed your last message, I'll update the firmware as well.

**Comment by Privatecoder** [comment]
> OK, got it. There is one topic I do not understand: I use the same waveshare with two ports, but only get one device -> this might be the problem. Michel

You will have two interfaces and two config options. Default IP are `192.168.1.200` for the first and `192.168.1.201` for the second port.

In your screenshot:

![image](https://github.com/Privatecoder/seplos-mqtt-remote-rs485/assets/45964815/0ca526f5-7391-4212-8944-b1754d2299c5)

Click multiple times (click and wait) on `Auto search` until it shows both. change their IPs to something within your IP range, i.e. `192.168.2.70` and `192.168.2.71`

**Comment by Privatecoder** [comment]
@mworion does this work for you know / can I close this issue? Also let me know what to put in the readme for others to not stumble upon similar issues.

**Comment by Privatecoder** [comment]
if there are any more issue please let me know.

**Comment by mworion** [comment]
Sorry being late, the important part so far was the hint of the update of the firmware. This helped. Now I'm testing around the usage etc. 
Thanks for all the help.
Michel
