### ISSUE TITLE
Open Questions

### ISSUE THREAD

**Issue by jwillmer** [Privatecoder/seplos-mqtt-remote-rs485#2]
Hi, thank you for the work you put into this. I have some questions while evaluating if  want to recreate it:

1) Why do I need to connect the RS485 device to CAN and COM OUT?
2) Do I need to connect two network cables to the RS485 device or is one enough?

**Comment by Privatecoder** [comment]
The port on the BMS is a dual-use port: It has pins for CAN and for RS485 communication.

When the BMS is set to _speak_ CAN to the inverter, one needs to split the port on the BMS to CAN (which then connects the inverter to the BMS) and RS485 (which is required to read the Masters Data – **and only the Master**).

Therefore: If you want to read multiple packs in parallel while connecting the Master to your inverter via CAN, you need three cables:

1) BMS <=> Inverter (CAN)
2) BMS <=> RS485_1 (RS485, baud 9600, Master via splitter)
3) BMS <=> RS485_2 (RS485, baud 19200, Slaves via one of the two empty RS485 ports on either the first (Master) or last pack)

**Comment by jwillmer** [comment]
Understood. Thank you. And what is with the network cable. Do I need one or two. I got confused since there are two IP's to configure and the RS485 device has two network ports.

**Comment by Privatecoder** [comment]
The Waveshare 2 Channel RS485 to ETH Adapter has two ethernet ports for daisy-chaining, i.e. it works like a two-port switch, meaning if you are using more than one of those, you can connect one of the ethernet ports to your switch/router and use the second port to connect to another adapter. In summary: You only need one ethernet-cable for the adapter to connect to your switch/router.
