### ISSUE TITLE
Destination IP/Port required?

### ISSUE THREAD

**Issue by jwillmer** [Privatecoder/seplos-mqtt-remote-rs485#3]
Is it required to set destination IP and port in Waveshare RS485?

I followed the setup and all seams to be working but I don't see any new device in my Home Assistant MQTT integration. Is there a way to confirm data is actually received by the seplos-mqtt-remote-rs485 container?

**Comment by Privatecoder** [comment]
have you restarted Home Assistant after starting the docker-container?
however you should always be able to see the published MQTT messages via something like MQTT Explorer

**Comment by Privatecoder** [comment]
also, when setting the Waveshare device to `Work Mode` `TCP Server`

<img width="287" alt="image" src="https://github.com/Privatecoder/seplos-mqtt-remote-rs485/assets/45964815/c961f05b-9528-4baa-a4c0-7eac0e42a10e">

the `Dest. IP/Domain` and `Dest. Port` are disabled

<img width="292" alt="image" src="https://github.com/Privatecoder/seplos-mqtt-remote-rs485/assets/45964815/82fd179d-94e0-4058-a596-9b4ae187744c">

**Comment by jwillmer** [comment]
This is what I configured for master (IP and Gateway I removed in the screenshot)
![image](https://github.com/Privatecoder/seplos-mqtt-remote-rs485/assets/1503577/e7f8e259-4a79-4438-acab-d1d3cf3cd28f)

**Comment by Privatecoder** [comment]
the web interface really doesn't work well so I recommend using the VirCom (Windows) tool (works in Windows for ARM on macOS as well).

However I would go ahead and check MQTT Explorer first to see if it receives anything.

**Comment by jwillmer** [comment]
Great. Now I see both packs in Home Assistant. Sadly all sensors are marked unavailable.

**Comment by Privatecoder** [comment]
see my previous message: check if the docker container actually retrieves data from the packs.

**Comment by jwillmer** [comment]
Ok, will do but can i be as simple as wrong wiring? Depending on the patch cable the colors are mapping to different pins:

![image](https://github.com/Privatecoder/seplos-mqtt-remote-rs485/assets/1503577/78a20ee0-8b6b-4757-ba62-a48c3f52c1c8)

**Comment by Privatecoder** [comment]
should look like this in MQTT Explorer:

<img width="463" alt="image" src="https://github.com/Privatecoder/seplos-mqtt-remote-rs485/assets/45964815/b6928cf7-a6e7-4502-a621-4cbf345534a8">

as for the wiring:

I used the 568B scheme

**Comment by jwillmer** [comment]
Resolved! The stupid keystone jacks did not work with flexible cables and I even had to bend the cutting blades to work with solid cables. But now it works and looks beautiful!
