### ISSUE TITLE
Container stops on power loss

### ISSUE THREAD

**Issue by jwillmer** [Privatecoder/seplos-mqtt-remote-rs485#5]
I rewired my Waveshare RS485 only to find out that the docker container stopped working afterwards. Can we keep the container running and trying to reconnect / self recover?

```
2024/03/01 23:22:29 socat[7] E read(7, 0x14b2a8c6c000, 8192): Connection reset by peer
ERROR:SeplosBMS:Serial port disconnected, cleaning up and exiting...
```

**Comment by Privatecoder** [comment]
if the container is started with `--restart unless-stopped` _any_ error will cause a restart of the container which can be considered `self recover` in my opinion

**Comment by jwillmer** [comment]
Good idea. Will do for now. But might not be the best for prolonged downtime.

**Comment by Privatecoder** [comment]
For prolonged downtimes, the container could be stopped. Adding a logic here would require monitoring `socat`which itself does not have built-in logic to retry a connection after it's been closed or reset.
