### ISSUE TITLE
Application stops regularly

### ISSUE THREAD

**Issue by jwillmer** [Privatecoder/seplos-mqtt-remote-rs485#6]
The docker container stops transmitting data every couple of days. A simple restart of the docker container resolves it. The last log output from the container today (before I restarted it) was the following:

```
    ...
    "no_calibration_of_voltage": "normal",
    "no_calibration_of_current": "normal",
    "no_calibration_of_null_point": "normal"
}
INFO:SeplosBMS:Pack1:Sending updated stats to mqtt.
INFO:SeplosBMS:Sending online status to mqtt
INFO:SeplosBMS:Pack0:Requesting data...
DEBUG:SeplosBMS:Pack0:telemetry_command: b'~20004642E00201FD36\r'
INFO:SeplosBMS:home assistant online, sending sensor configs
```

**Comment by smagicld** [comment]
I had the same problem. add timeout to the serial connection:
SERIAL_SLAVES_INSTANCE = serial.Serial(port='/dev/ttyUSB0', baudrate=19200, **timeout=0.501750**)

**Comment by jwillmer** [comment]
> I had the same problem. add timeout to the serial connection:
> SERIAL_SLAVES_INSTANCE = serial.Serial(port='/dev/ttyUSB0', baudrate=19200, **timeout=0.501750**)

Only for the slave or in general?

**Comment by Privatecoder** [comment]
also: is there any specific reason for this timeout value?

**Comment by jwillmer** [comment]
@Privatecoder I guess it does not heart. If we run into a timeout the app stops and will be restarted. If we do not set it we might end up in a deadlock. I updated my pull request with it.

**Comment by Privatecoder** [comment]
I was just wondering about the `0.501750`– if that value was chosen for any specific reason..?

**Comment by jwillmer** [comment]
same question but i guess not. I did not use any specific time.

**Comment by Privatecoder** [comment]
can we close this now or is this still a problem for anyone?

**Comment by jwillmer** [comment]
Already pulled last release. Awesome teamwork this night :)
